# CI Code for generating and publishing beta assets

name: publish_assets
on:
  release:
    types: [published]
jobs:
  generate_assets:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout moontest
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.ref }}

    - name: Build Beta Assets
      if: ${{ github.event.release.prerelease  }}
      run: ./scripts/build-zip-release.sh -b

    - name: Build Stable Assets
      if: ${{ !github.event.release.prerelease  }}
      run: ./scripts/build-zip-release.sh

    - name: Upload assets
      run: |
        gh release upload ${{ env.TAG }} ${{ env.FILES }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FILES: >
          ${{ github.workspace }}/.dist/moontest.zip
          ${{ github.workspace }}/.dist/RELEASE_INFO
          ${{ github.workspace }}/.dist/COMMIT_LOG
        TAG: ${{ github.event.release.tag_name }}
